# Generated by Django 6.0 on 2025-12-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
